apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
  labels:
    app: node-backend
spec:
  type: NodePort
  selector:
    app: node-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32319
