[phases]
setup = "curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs"

[install]
commands = ["cd backend && npm install", "cd frontend && npm install"]

[build]
commands = ["cd frontend && npm run build"]

[start]
commands = ["cd backend && npm start"]
