[phases.setup]
commands = [
  "cd backend && npm install",   # Install backend dependencies
  "cd frontend && npm install"  # Install frontend dependencies
]

[phases.build]
commands = [
  "cd frontend && npm run build"  # Build the frontend React app
]

[phases.start]
commands = [
  "cd backend && npm start"  # Start the backend server
]
